# Generated by Django 3.0.1 on 2022-03-30 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(max_length=2500)),
                ('autor', models.TextField(max_length=15)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appblog.Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=15)),
                ('comentario', models.TextField(max_length=250)),
                ('posteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.Posteos')),
            ],
        ),
    ]
