# Generated by Django 3.0.1 on 2022-03-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_remove_posteos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='posteo',
        ),
    ]
