# Generated by Django 3.0.1 on 2022-03-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0004_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
