# Generated by Django 3.0.1 on 2022-05-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0006_avatar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatares'),
        ),
    ]
