# Generated by Django 3.0.1 on 2022-05-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0008_posteos_encabezado_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteos',
            old_name='encabezado_imagen',
            new_name='imagen_post',
        ),
    ]
